language: ruby
rvm:
  # - 1.9.3
  # - 1.9.2
  - 2.0.0
  - 2.1.0
  # - ruby-head
  # - jruby-19mode
  # - jruby-head

notifications:
  email:
    on_success: change
    on_failure: always

script: bundle exec rspec spec